---
- name: assert required variables are set and have reasonable values
  assert:
    that:
      - (landscape_olafnorge_de_labels | length) > 0
      - (landscape_olafnorge_de_network_definitions | length) > 0
      - (landscape_olafnorge_de_networks | length) > 0
      - landscape_olafnorge_de_environment is defined
      - landscape_olafnorge_de_environment.db_pass is defined
      - (landscape_olafnorge_de_environment.db_pass | length) > 0
      - landscape_olafnorge_de_environment.db_landscape_pass is defined
      - (landscape_olafnorge_de_environment.db_landscape_pass | length) > 0
      - landscape_olafnorge_de_environment.rabbitmq_password is defined
      - (landscape_olafnorge_de_environment.rabbitmq_password | length) > 0
      - landscape_olafnorge_de_environment.smtp_pass is defined
      - (landscape_olafnorge_de_environment.smtp_pass | length) > 0

- name: create secrets for landscape.example.com
  docker_secret:
    data: "{{ item.value.data }}"
    name: "{{ item.value.name }}"
    state: present
  no_log: yes
  with_dict: "{{ landscape_olafnorge_de_secrets }}"
  when: landscape_olafnorge_de_use_secrets | bool

- name: spawn landscape.example.com service
  docker_stack:
    compose:
      - "{{ landscape_olafnorge_de_compose }}"
    name: "{{ landscape_olafnorge_de_name }}"
    prune: yes
    state: present
